# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(439, 744)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.studentsTable = QtWidgets.QTableWidget(self.centralWidget)
        self.studentsTable.setObjectName("studentsTable")
        self.studentsTable.setColumnCount(3)
        self.studentsTable.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.studentsTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.studentsTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.studentsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.studentsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.studentsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.studentsTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.studentsTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.studentsTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.studentsTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.studentsTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.studentsTable.setItem(1, 2, item)
        self.studentsTable.horizontalHeader().setVisible(True)
        self.studentsTable.horizontalHeader().setStretchLastSection(True)
        self.studentsTable.verticalHeader().setVisible(False)
        self.studentsTable.verticalHeader().setHighlightSections(True)
        self.verticalLayout.addWidget(self.studentsTable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(11, 6, 11, 11)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.newEntryButton = QtWidgets.QPushButton(self.centralWidget)
        self.newEntryButton.setObjectName("newEntryButton")
        self.horizontalLayout.addWidget(self.newEntryButton)
        self.saveButton = QtWidgets.QPushButton(self.centralWidget)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 439, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuDatei = QtWidgets.QMenu(self.menuBar)
        self.menuDatei.setObjectName("menuDatei")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionSpeichern = QtWidgets.QAction(MainWindow)
        self.actionSpeichern.setObjectName("actionSpeichern")
        self.menuDatei.addAction(self.actionSpeichern)
        self.menuBar.addAction(self.menuDatei.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Studentenverwaltung"))
        item = self.studentsTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.studentsTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.studentsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Vorname"))
        item = self.studentsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nachname"))
        item = self.studentsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Studienfach"))
        __sortingEnabled = self.studentsTable.isSortingEnabled()
        self.studentsTable.setSortingEnabled(False)
        item = self.studentsTable.item(0, 0)
        item.setText(_translate("MainWindow", "Max"))
        item = self.studentsTable.item(0, 1)
        item.setText(_translate("MainWindow", "Mustermann"))
        item = self.studentsTable.item(0, 2)
        item.setText(_translate("MainWindow", "Informatik"))
        item = self.studentsTable.item(1, 0)
        item.setText(_translate("MainWindow", "Erika"))
        item = self.studentsTable.item(1, 1)
        item.setText(_translate("MainWindow", "Mustermann"))
        item = self.studentsTable.item(1, 2)
        item.setText(_translate("MainWindow", "Mathematik"))
        self.studentsTable.setSortingEnabled(__sortingEnabled)
        self.newEntryButton.setText(_translate("MainWindow", "Neuen Eintrag"))
        self.saveButton.setText(_translate("MainWindow", "Speichern"))
        self.menuDatei.setTitle(_translate("MainWindow", "Datei"))
        self.actionSpeichern.setText(_translate("MainWindow", "Speichern"))

